<?php
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);
require '../vendor/autoload.php';
require 'config.php';


use GuzzleHttp\Client;
$client = new Client();
$client->setDefaultOption('verify', false);

$input = $_GET['error'];
$input = str_replace( array( "'","'" ),'',$input );
$url = 'https://' . $instance . '.service-now.com/api/now/v1/table/incident';

$response = $client->post($url, [
    'json' => [
            'short_description' => 'The Plotter Has The Following Error: ' . $input
            ,'description' => 'The Plotter Has The Following Error: ' . $input . ' --THIS TICKET GENERATED BY THE BYPANIC BUTTON--'
            ,'comments' => 'THIS TICKET GENERATED BY THE PANIC BUTTON'
            ,'urgency' => 4
            ,"u_ci_business_criticality" => "Infrastructure Service"
            ,'location' => '14d6d81737963140859627d2b3990e9e'
            ,"approval"=> "not requested"
            ,"u_environment"=> "Production"
            ,"severity"=> "3"
            ,"assignment_group"=>'c76584260f2a31004758e388b1050e09'
            ,"u_department"=> "d01ed55cdbbe9b40ea9ff5161d9619af"
            ,"u_building_location"=> "York"
            ,"caller_id" => 'b62c60b537c27100859627d2b3990efd'
    ],
    'auth' => [
        $username, 
        $password
    ]
]);

$body = $response->getBody();
$data = json_decode($body);
$return = array(
    'number' => $data->result->number
    ,'error' => $input
);
print json_encode($return);
