<?php
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);
require '../vendor/autoload.php';
require 'config.php';


use GuzzleHttp\Client;
$client = new Client();
$client->setDefaultOption('verify', false);

$input = $_GET['error'];
$input = str_replace( array( "'","'" ),'',$input );
$url = 'https://' . $instance . '.service-now.com/api/now/v1/table/incident';

$response = $client->post($url, [
    'json' => [
            'short_description' => 'The Plotter Has The Following Error: ' . $input
            ,'description' => 'The Plotter Has The Following Error: ' . $input . ' --THIS TICKET GENERATED BY THE BYPANIC BUTTON--'
            ,'comments' => 'THIS TICKET GENERATED BY THE PANIC BUTTON'
            ,'urgency' => 4
    ],
    'auth' => [
        $username, 
        $password
    ]
]);

$body = $response->getBody();
$data = json_decode($body);
$return = array(
    'number' => $data->result->number
    ,'error' => $input
);
print json_encode($return);
